package alphabetic.metier.entite;

import generique.metier.entite.Individu;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;
import lombok.ToString;

/**
 * EN - Class Type representing the entity manipulated by the generic genetic algorithm
 *      Here a Word allowing the research of a mystery word
 * FR - Classe Type représentant l'entité manipulé par l'algorythme génétique générique
 *      Ici un Mot permettant la recherche d'un mot mystère
 *       
 * @author Parlons Archi !
 * @see <a href="https://www.youtube.com/@christophecadet" /a>
 * 
 * @version 1.0
 */
@ToString
public class Mot implements Individu<String>{

	
	/**
	 * EN - Version of the class allowing serialization
	 * FR - Version de la class permettant la sérialisation
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * EN - Value of the word constituted by a String
	 * FR - Valeur du mot constitué par une chaine de caractères
	 */
	@Getter
	@Setter
	@NonNull
	private String valeur;
	
	/**
	 * EN - Score of the word obtained at the last evaluation
	 *      The value -1 indicates that the word has never been evaluated, the minimum score obtained from the evaluation being zero
	 * FR - Score du mot obtenu à la dernière évaluation
	 * 		La valeur -1 permet d'indiquer que le mot n'a jamais été évalué, la note minimale obtenue suite à l'évaluation étant zéro
	 */
	@Getter
	@Setter
	private int score;
	
	/**
	 * EN - Indicates whether the word has been selected to participate in child word generation
	 * FR - Indique si le mot a été sélectionné pour participer à la génération de mots enfants
	 */
	@Getter
	@Setter
	private boolean selectionne;
	
	/**
	 * EN - Indicates whether the word was generated by crossing parent words
	 * FR - Indique si le mot a été généré par croisement de mots parents
	 */
	@Getter
	@Setter
	private boolean enfant;

	/**
	 * EN - Indicates if the word is the mystery word and therefore if it is a solution
	 * FR - Indique si le mot est le mot mystère recherché et donc si il constitue une solution
	 */
	@Getter
	@Setter
	private boolean solution;
	
	
	/**
	 * EN - Constructor of the class
	 *      param value - word value
	 * FR - Construteur de la classe
	 * 	    @param valeur valeur du mot
	 */
	public Mot(String valeur) {
		setValeur(valeur);
		
		/* EN - Initial score of the word
		 *      The value -1 indicates that the word has never been evaluated, the minimum score obtained after the evaluation being zero
		 * FR - Score initial du mot
		 * 		La valeur -1 permet d'indiquer que le mot n'a jamais été évalué, la note minimale obtenue suite à l'évaluation étant zéro
		 */
		score = -1;
	}



}
